# Starter pipeline


trigger:
  - main
  
  pool:
    vmImage: ubuntu-latest
  
  steps:
  - task: KubernetesManifest@0
    inputs:
      action: 'deploy'
      kubernetesServiceConnection: 'eks-mundos-e-2'
      manifests: 'nginx-deployment.yaml'